<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UCEN89R" failures="1" tests="1" name="Positive test" time="4.004" errors="0" timestamp="2024-03-09T20:48:31 EET">
  <testcase classname="tests.PositiveTest" name="logInTest" time="2.587">
    <failure type="java.lang.AssertionError" message="actualSuccessMessage does not contain expectedSuccessMessage
expectedSuccessMessage: You logged into a secure are!
actualSuccessMessage: You logged into a secure area!
× expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: actualSuccessMessage does not contain expectedSuccessMessage
expectedSuccessMessage: You logged into a secure are!
actualSuccessMessage: You logged into a secure area!
× expected [true] but found [false]
at tests.PositiveTest.logInTest(PositiveTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- logInTest -->
</testsuite> <!-- Positive test -->
